name: 🧭 Auto Sitemap & SEO Updater (MystAI v2.4)

on:
  schedule:
    - cron: '0 4 * * 1' # Her Pazartesi sabah 04:00’te çalışır (UTC)
  workflow_dispatch: # Manuel çalıştırmaya izin verir

jobs:
  update_sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate sitemap
        run: |
          # Eski dosya varsa sil
          rm -f sitemap.xml

          # Dosyayı sıfırdan oluştur (BOM'suz ve boşluksuz)
          printf '<?xml version="1.0" encoding="UTF-8"?>\n' > sitemap.xml
          printf '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' >> sitemap.xml

          for url in "/" "/about.html" "/privacy.html" "/terms.html" "/disclaimer.html" "/contact.html"; do
            printf "  <url><loc>https://mystai.ai%s</loc><changefreq>weekly</changefreq><priority>0.8</priority></url>\n" "$url" >> sitemap.xml
          done

          printf '</urlset>\n' >> sitemap.xml

      - name: Deploy sitemap to site root
        run: |
          mkdir -p ./public
          mv sitemap.xml ./public/sitemap.xml
          echo "✅ Sitemap moved to /public/sitemap.xml"

      - name: Ping search engines
        run: |
          echo "🔔 Pinging Google, Bing, Yandex and Yahoo..."
          curl -s "https://www.google.com/ping?sitemap=https://mystai.ai/sitemap.xml"
          curl -s "https://www.bing.com/ping?sitemap=https://mystai.ai/sitemap.xml"
          curl -s "https://yandex.com/ping?sitemap=https://mystai.ai/sitemap.xml"
          curl -s "https://search.yahoo.com/ping?sitemap=https://mystai.ai/sitemap.xml"

      - name: Done
        run: echo "🎉 MystAI sitemap başarıyla sıfırdan oluşturuldu ve bildirildi!"
